# Generated by Django 3.2 on 2021-04-28 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Minyuka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('発注番号', models.CharField(max_length=40)),
                ('発注先', models.CharField(max_length=40)),
                ('納期', models.DateField(blank=True, null=True)),
                ('個数', models.IntegerField(blank=True, null=True)),
                ('読込日', models.DateField(blank=True, null=True)),
                ('品名', models.CharField(blank=True, max_length=40)),
                ('mmm', models.IntegerField(blank=True, null=True)),
                ('備考', models.CharField(blank=True, max_length=40)),
                ('入荷FLG', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_no', models.CharField(max_length=40)),
                ('o_no', models.CharField(max_length=40)),
                ('c_name', models.CharField(max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('c_date', models.DateField(blank=True, null=True)),
                ('購入納期', models.DateField(blank=True, null=True)),
                ('出荷日', models.DateField(blank=True, null=True)),
                ('手配残', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
