# Generated by Django 3.2 on 2021-04-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='購入納期',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
