# Generated by Django 3.2 on 2021-04-15 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0002_post_購入納期'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='購入納期',
            new_name='s_date',
        ),
    ]
