# Generated by Django 3.2 on 2021-04-15 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0003_rename_購入納期_post_s_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='s_date',
            new_name='購入納期',
        ),
    ]
