# Generated by Django 3.2 on 2021-04-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0004_rename_s_date_post_購入納期'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='p_no',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
