# Generated by Django 3.2 on 2021-04-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0005_auto_20210416_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='出荷日',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
