# Generated by Django 3.2 on 2021-04-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0007_auto_20210416_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='c_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
