# Generated by Django 3.2 on 2021-04-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0008_alter_post_c_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='購入納期',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
