# Generated by Django 3.2 on 2021-04-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0011_auto_20210416_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='購入納期',
            field=models.DateField(blank=True, null=True),
        ),
    ]
