# Generated by Django 3.2 on 2021-04-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0013_auto_20210416_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='c_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='購入納期',
            field=models.DateField(blank=True, null=True),
        ),
    ]
