# Generated by Django 3.2 on 2021-04-23 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0014_auto_20210419_0952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minyuka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('発注番号', models.CharField(max_length=40)),
                ('発注先', models.CharField(max_length=40)),
                ('納期', models.DateField(blank=True, null=True)),
                ('個数', models.IntegerField(blank=True, null=True)),
                ('読込日', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='c_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='o_no',
            field=models.CharField(max_length=40),
        ),
    ]
