# Generated by Django 3.2 on 2021-04-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0015_auto_20210423_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='minyuka',
            name='品名',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
