# Generated by Django 3.2 on 2021-04-23 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0018_rename_id_minyuka_m_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minyuka',
            name='m_id',
        ),
    ]
