# Generated by Django 3.2 on 2021-04-23 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0020_minyuka_m_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='minyuka',
            old_name='m_id',
            new_name='mmm',
        ),
    ]
