# Generated by Django 3.2 on 2021-04-23 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0021_rename_m_id_minyuka_mmm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='minyuka',
            name='mmm',
        ),
    ]
