# Generated by Django 3.2 on 2021-04-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0023_minyuka_mmm'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='手配残',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
