# Generated by Django 3.2 on 2021-04-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0024_post_手配残'),
    ]

    operations = [
        migrations.AddField(
            model_name='minyuka',
            name='備考',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
