# Generated by Django 3.2 on 2021-04-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit', '0025_minyuka_備考'),
    ]

    operations = [
        migrations.AddField(
            model_name='minyuka',
            name='入荷FLG',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
